// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvntfcjunyegdsdxclpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bnRmY2p1bnllZ2RzZHhjbHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTU0NTAsImV4cCI6MjA2NjY3MTQ1MH0.vqgggPuh6CGWAqv-M0XiJhP2EId8hxhMm-8FcuAqF-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});